### ISSUE TITLE
Confusing change in object formatting in v2

### ISSUE THREAD

**Issue by ErrorEater** [ocoanet/ProtoUntyped#4] opened 2023-06-06 23:04 UTC
The changed formatting of objects in v2 is confusing. It converts an empty object to an empty string now.
Before v2 it was possible to understand that a field holds an empty object with optional fields but now it looks like a string.

I claim it should be an object and not a string because on the messages I'm trying to decode I see that this field, depending on a condition, sometimes contains an object with values and sometimes it's empty when those values are not specified.

Base64 encoded message:
`CgAQGBogZDg0MzJmYzEwOTQyNGM1NWE5ZTAxYmIyYWFmNjUzMDk=`

Decoded as follows on v1.0.1:
```
message {
- 1 = message {
    }
- 2 = 24
- 3 = "d8432fc109424c55a9e01bb2aaf65309"
}
```

And became as follows on v2.0.0:
```
message {
- 1 = ""
- 2 = 24
- 3 = "d8432fc109424c55a9e01bb2aaf65309"
}
```

Seems v1.0.1 decoding is correct.

**Comment by ocoanet** [comment] 2023-06-07 12:31
In your encoded message, the first field has the wire type 2 (LEN), which can be used for strings, bytes or embedded messages.
The content of the field could theoretically help us to identify the message field type, but here the content is empty.
It is typical situation where the content type is ambiguous.

I agree that deciding to identify the field as a string here is subject to debate. However, if the library decided to identify it as an empty object, someone else could also open an issue claiming that the field should be identified as a string or as an empty byte array.

In my view, identifying the field as a string here is a good choice because empty strings are probably more common than empty objects. I could change my mind on this behavior, but I doubt that this issue deserves too much discussion. I think that we should embrace the fact that the "untyped" decoding is by design imperfect.

If you really need to identify the empty strings as empty objects, I can provide additional decoding options, for example `options.DefaultStringDecodingType = StringDecodingType.Object`.

What do you think?

**Comment by ErrorEater** [comment] 2023-06-07 15:11
I think if the type is not known a broader data type like object should be used. Making it string suggests it's type is string while it's just a place holder for unknown type.
I think you should go .NET way. Everything is derived from object.

**Comment by ocoanet** [comment] 2023-06-08 15:58
Closed by: https://github.com/ocoanet/ProtoUntyped/commit/dea902884943c84b3dac8588a802eb2e0b115ac1
It will be available in the next release.

**Closed as completed by ocoanet** 2023-06-08 15:58 UTC

**Comment by ocoanet** [comment] 2023-06-09 07:00
@aliveli186 What do you think of using a specific format for empty strings, either:
```
message {
- 1 = { }
- 2 = 24
- 3 = "d8432fc109424c55a9e01bb2aaf65309"
}
```

or:
```
message {
- 1 = empty
- 2 = 24
- 3 = "d8432fc109424c55a9e01bb2aaf65309"
}
```

It would not change the decoded  `ProtoObject` itself but at least the `ToString` output would be slightly more explicit.

**Comment by ErrorEater** [comment] 2023-06-09 13:44
I think v1 notation with message prefix was fine.
message {
}

If you want to be more compact the last curly brackets can be moved up. But I think message prefix should stay, it intuitively tells there is a separate object there.
But you can remove the dash (-) before the field numbers to make the text more clear and less confusing with a negative number.
